name: Selenoid Sprint_9
on:
  push:
    branches:
      - main
      - develop
jobs:
  run-selenoid-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code  
        uses: actions/checkout@v3
      - name: Pull selenoid image
        run: docker pull selenoid/chrome:128.0
      - name: Create directories
        run: |
          mkdir -p video logs allure-results
      - name: Run tests in docker
        run: docker compose up --build --exit-code-from selenium-tests
      - name: Upload Allure results
        if: always()  
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: ./allure-results
      
      - name: Upload video logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-videos
          path: ./video
      
      - name: Stop containers
        if: always()
        run: docker compose down
      